/*

 BORDER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : F:\PROGRAMMING\GameBoy\Projects\RYC-GBDK\res\border.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __border_map_h_INCLUDE
#define __border_map_h_INCLUDE

#define border_mapWidth 20
#define border_mapHeight 6
#define border_mapBank 0

extern const unsigned char border_map[];

#endif

/* End of BORDER_MAP.H */
