/*

 BORDER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : F:\PROGRAMMING\GameBoy\Projects\RYC-GBDK\res\border.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Dialog_Border_map_h_INCLUDE
#define __Dialog_Border_map_h_INCLUDE

#define Dialog_Border_map_Width 20
#define Dialog_Border_map_Height 6
#define Dialog_Border_map_Bank 0

extern const unsigned char Dialog_Border_map[];

#endif

/* End of BORDER_MAP.H */
