/*

 DIALOG_BORDER_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Dialog_Border_sprite_h_INCLUDE
#define __Dialog_Border_sprite_h_INCLUDE

/* Bank of tiles. */
#define Border_sprite_Bank 0
/* Start of tile array. */
extern const unsigned char Dialog_Border_sprite[];

#endif

/* End of DIALOG_BORDER_SPRITE.H */
