/*

 LEVEL1_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : F:\PROGRAMMING\GameBoy\Projects\RYC-GBDK\res\level_one.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level1_1_h_INCLUDE
#define __level1_1_h_INCLUDE

#define level1_1Width 20
#define level1_1Height 18
#define level1_1Bank 0

extern const unsigned char level1_1[];

#endif

/* End of LEVEL1_1.H */
