/*

 LEVEL1_1_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 75

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Level1_1_sprite_h_INCLUDE
#define __Level1_1_sprite_h_INCLUDE

/* Bank of tiles. */
#define Level1_1_sprite_Bank 0
#define Level1_1_sprite_size 76
/* Start of tile array. */
extern const unsigned char Level1_1_sprite[];

#endif

/* End of LEVEL1_1_SPRITE.H */
