/*

 LEVEL1_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : F:\PROGRAMMING\GameBoy\Projects\RYC-GBDK\res\level_one.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Level1_1_h_INCLUDE
#define __Level1_1_h_INCLUDE

#define Level1_1_Width 20
#define Level1_1_Height 18
#define Level1_1_Bank 0

extern const unsigned char Level1_1_map[];

#endif

/* End of LEVEL1_1.H */
