/*

 MAINCHARACTER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MainCharacter_h_INCLUDE
#define __MainCharacter_h_INCLUDE

/* Bank of tiles. */
#define MainCharacterBank 0
/* Start of tile array. */
extern const unsigned char MainCharacter_sprite[];

#endif

/* End of MAINCHARACTER.H */
