/*

 TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : F:\PROGRAMMING\GameBoy\Projects\RYC-GBDK\res\test.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __test_h_INCLUDE
#define __test_h_INCLUDE

#define testWidth 20
#define testHeight 18
#define testBank 0

extern const unsigned char test[];

#endif

/* End of TEST.H */
